const doctorsData = [
  {
    id: 1,
    name: "Доктор Иванов",
    experience: "Не более 5 лет",
    gender: "Мужской",
    category: "Первая",
    academicDegree: "Кандидат медицинских наук",
    rating: 4.8,
    numberOfReviews: 56,
    admissionType: "Очное",
  },
  {
    id: 2,
    name: "Доктор Петрова",
    experience: "От 5 до 10 лет",
    gender: "Женский",
    category: "Вторая",
    academicDegree: "Доктор медицинских наук",
    rating: 5,
    numberOfReviews: 24,
    admissionType: "Заочное",
  },
  {
    id: 3,
    name: "Доктор Анна",
    experience: "От 5 до 10 лет",
    gender: "Женский",
    category: "Вторая",
    academicDegree: "Доктор медицинских наук",
    rating: 2.4,
    numberOfReviews: 72,
    admissionType: "Заочное",
  },
  {
    id: 4,
    name: "Доктор Алексей",
    experience: "Свыше 20 лет",
    gender: "Мужской",
    category: "Вторая",
    academicDegree: "Доктор медицинских наук",
    rating: 3,
    numberOfReviews: 101,
    admissionType: "Заочное",
  },
  {
    id: 5,
    name: "Иванова Мария Давидовна",
    experience: "От 10 до 20 лет",
    gender: "Женский",
    category: "Высшая",
    academicDegree: "Кандидат медицинских наук",
    rating: 5,
    numberOfReviews: 22,
    admissionType: "Очное",
  },
  {
    id: 6,
    name: "Чатинян Гарик Артурович",
    experience: "Свыше 20 лет",
    gender: "Мужской",
    category: "Высшая",
    academicDegree: "Кандидат медицинских наук",
    rating: 4.2,
    numberOfReviews: 22,
    admissionType: "Очное",
  },
  // Добавьте других врачей с аналогичными данными
];

export default doctorsData;
